### ISSUE TITLE
Change suggestion to prevent unwanted servo behavior

### ISSUE THREAD

**Issue by vef445** [jlecomte/ascom-telescope-cover-v2#1]
Hi Julien,
First of all, thank you for sharing this new version of your motorized cover. While I'm not gonna make any use of the calibrator part of it, being able to remotely cover and uncover my two telescopes is a huge benefit for me.

When running the current release, I noticed that my servo would move (full speed) almost 90deg each time it was powered up, which is exactly what we try to avoid with using feedback.
I added some verbose to the Arduino code and noticed that when in "close" position, the value of "pos" was below 0 (around -5). Same unwanted result in "open" position, with a "pos" reporting a value above 180 (around 190).

Here is the code change that I'd like to suggest to you and which fixes the issue:

From

> if (servoCalibrationData.magicNumber == NVM_MAGIC_NUMBER) {
>     // Short delay, so that the servo has been fully initialized.
>     // Not 100% sure this is necessary, but it won't hurt.
>     delay(100);
>     int feedbackValue = analogRead(SERVO_FEEDBACK_PIN);
>     pos = (int)((feedbackValue - servoCalibrationData.intercept) / servoCalibrationData.slope);
>   }

To

> if (servoCalibrationData.magicNumber == NVM_MAGIC_NUMBER) {
>     // Short delay, so that the servo has been fully initialized.
>     // Not 100% sure this is necessary, but it won't hurt.
>     delay(100);
>     int feedbackValue = analogRead(SERVO_FEEDBACK_PIN);
>     pos = (int)((feedbackValue - servoCalibrationData.intercept) / servoCalibrationData.slope);
>     if ( pos < 0 ) {
>       pos = 0;
>     }
>     if ( pos > 180 ) {
>       pos = 180;
>     }
>   }

Best,
Guillaume

**Comment by jlecomte** [comment]
Done, in [this commit](https://github.com/jlecomte/ascom-telescope-cover-v2/commit/044a117fa27519f7e16e70ed0cb1b7999052442b). Thanks!
