### ISSUE TITLE
servo motor experiences jolts #12 - related to your archived version V1

### ISSUE THREAD

**Issue by 730522js** [jlecomte/ascom-telescope-cover-v2#2]
Hi Dark Sky Geek and many thanks for sharing your work with the community !!!

I've recently started using you Telescope Cover (v1) for which I saw you archived the repo.

I've also experienced an issue reported by user [jduffas](https://github.com/jduffas) => (servo motor experiences jolts #12) for the V1 of the telescope cover.

I'm sorry if i waste your time by opening an issue here but as that other repository (v1) was archived in Sep 2024 I though I could reach you here.

I found a workaround for the jolts of the motor and I thought to share it so perhaps somebody could make use of the workaround.

I've figured the torque does not need to be held by the code so if I disconnect the servo after each operation and reconnect it before each operation the jolts no longer occur, Here's how i changed the openCover and closeCover parts:
```
void openCover() {
    servo.attach(9); // Attach the servo to pin 9
    int pos = servo.read();

    if (pos < 180) {
        for (; pos <= 180; pos++) {
            servo.write(pos);
            delay(30); // Adjust as needed for smooth movement
        }
    }

    servo.detach(); // Detach the servo to stop holding position
    state = open;
}

void closeCover() {
    servo.attach(9); // Attach the servo to pin 9
    int pos = servo.read();

    if (pos > 0) {
        for (; pos >= 0; pos--) {
            servo.write(pos);
            delay(30); // Adjust as needed for smooth movement
        }
    }

    servo.detach(); // Detach the servo to stop holding position
    state = closed;
}
```

I hope this helps somebody.
Thanks again and take it easy!
John.

**Comment by jlecomte** [comment]
`servo.read()` will not return the *real* position of the cover. It merely returns the last value passed to `servo.write()` ([reference](https://docs.arduino.cc/libraries/servo/)). Therefore, if you manually move the cover when the servo is not powered, and then power the servo (`servo.attach()` + `servo.write()`), it will most definitely jerk.

The only real way to get rid of this while still using a servo is to use what I did in the v2 of this project (i.e., in this repo), which is to use a servo with analog feedback.
